# Site settings
title: DevOps Consultant
email: josh.beaureg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Most people like to get things done. I like to do things better.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sanguis.github.io" # the base hostname & protocol for your site
twitter_username: sanguisdev
github_username:  sanguis

# Build settings
markdown: kramdown
